project_id = "veajgqbhiuosazaklerm"

[api]
enabled = true
port = 54321

[functions.generate-insights]
verify_jwt = true

[functions.update-stocks]
verify_jwt = true

[functions.analyze-spending]
verify_jwt = true

[functions.categorize-transaction]
verify_jwt = true

[functions.market-analysis]
verify_jwt = true